### ISSUE TITLE
Installing from Vagrant idle installing 

### ISSUE THREAD

**Issue by maquineh** [Kong/kong-vagrant#87] opened 2018-04-27 15:52 UTC
I´ve been tryinng install kong using vagrant but when i use vagrant up after downloading and set up cassandra, i receive the message 'installing kong...' in the console but nothing happens. After 3 hours with message of installing  i quit installation and restart vagrant. the VM is installed but Kong is not.

I saw kong.deb file and after tried to install using dpkg but not work. So, after i dowloaded community deb version and installed direct on the VM.

![kongdeb](https://user-images.githubusercontent.com/4211623/39372038-53d69bb8-4a11-11e8-977e-4db9dc4bf497.png)

**Comment by Tieske** [comment] 2018-04-29 22:33
I could reproduce, but not fix the issue. When I replace the `wget` command by an equivalent `curl` one, it works, but it fails slightly later, hanging again.

It looks like an issue with the underlying VirtualBox or Vagrant tooling.

**Comment by Tieske** [comment] 2018-06-27 08:07
I tested again today, after updating to latest VirtualBox and latest Vagrant, and now it works for me.

Can you give it another try?

PS. on one occasion while it was hanging, I noticed in the VirtualBox GUI that the VM had switched from "running" to "paused". After resuming the VM, provisioning continued and finished successfully.

**Comment by maquineh** [comment] 2018-06-27 13:03
Ok I'll try again .

**Comment by Tieske** [comment] 2018-07-14 10:58
@maquineh Try checking the logs of the VirtualBox VM created by Vagrant. I've seen occasions where the VM gave out-of-memory errors, which caused VirtualBox to pause the VM.

Note that the VM by default is started with 4GB memory, which might be too much depending on the host system hardware. You can try [setting the `KONG_VB_MEM` environment variable](https://github.com/Kong/kong-vagrant#environment-variables-and-configuration) to a lower memory size. But be aware that it might cause other issues because the box runs Cassandra, Postgres, Redis, and Kong.

I'm closing this now. Feel free to reopen if this did not resolve it.

**Closed by Tieske** 2018-07-14 10:58 UTC

**Comment by maquineh** [comment] 2018-07-16 13:47
i tried with a 8gb RAM machine, but as you said before, after updating vagrant and virtualbox the problem is gone. Thanks
